version: 0.2

env:
  variables:

    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID  # Przekazywanie zmiennej z GitHub Secrets
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY  # Przekazywanie zmiennej z GitHub Secrets
    API_KEY: $API_KEY  # Jeśli masz inny sekret, który chcesz przekazać

phases:
  install:
    commands:
      - echo "DEp INIT"
      - echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
      - echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
      - echo "API_KEY: $API_KEY"  # Wyświetlanie API key z zmiennych środowiskowych

  build:
    commands:
      - echo "START "
      - mvn clean install 
