
spring:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  flyway:
    baseline-on-migrate: true


openai:
  api-key: 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
newsapi:
  api-key: 29744a376c0d408fb5eee8b3dd2d73b8
database:
  password: sa
server:
  port: 8081
