name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 13.48.79.235
          username: ec2-user
          key: ${{ secrets.AWS_PEM }}
          source: target/*.jar
          target: ~/app/

      - name: Start application on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 13.48.79.235
          username: ec2-user
          key: ${{ secrets.AWS_PEM }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar ~/app/*.jar > ~/app/app.log 2>&1 &