name: Deploy to AWS

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # użyj sekretu z GitHub
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # użyj sekretu z GitHub
          aws-region: "eu-north-1"  # Ustaw region, jeśli masz inny, zmień na odpowiedni

      - name: Run CodeBuild
        run: |
          aws codebuild start-build --project-name SimpleMavenBuildService  # Nazwa twojego projektu CodeBuild
