name: Deploy App 2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PEM key
        run: |
          echo "${{ secrets.AWS_PEM }}" > key.pem
          chmod 600 key.pem

      - name: Ensure Docker network exists on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@51.20.68.13 << EOF
            docker network inspect my-network >/dev/null 2>&1 || docker network create my-network
          EOF

      - name: Ensure app2 directory exists on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@51.20.68.13 << EOF
            mkdir -p ~/app2
          EOF

      - name: Remove existing containers on port 8081
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@51.20.68.13 << EOF
            CONTAINER_ID=\$(docker ps -q --filter "publish=8081")
            if [ -n "\$CONTAINER_ID" ]; then
              docker stop \$CONTAINER_ID
              docker rm \$CONTAINER_ID
            fi
          EOF

      - name: Run unit tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify build outputs
        run: |
          ls -lh target/*.jar
          ls -lh Dockerfile

      - name: Push application files to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no target/*.jar ec2-user@51.20.68.13:~/app2/
          scp -i key.pem -o StrictHostKeyChecking=no Dockerfile ec2-user@51.20.68.13:~/app2/

      - name: List files in ~/app2 on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@51.20.68.13 << EOF
            ls -lh ~/app2
          EOF

      - name: Rename JAR file on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@51.20.68.13 << EOF
            JAR_FILE=\$(ls ~/app2/*.jar 2>/dev/null | head -n 1)
            if [ -z "\$JAR_FILE" ]; then
              echo "No JAR file found in ~/app2"
              exit 1
            else
              mv "\$JAR_FILE" ~/app2/app.jar
            fi
          EOF

      - name: Run Docker container on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@51.20.68.13 << EOF
            cd ~/app2/
            docker build -t my-spring-boot-app-2 .
            docker run -d --network my-network -p 8081:8081 --name spring-boot-container-2 my-spring-boot-app-2
          EOF

      - name: Test container status on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@51.20.68.13 << EOF
            docker ps | grep spring-boot-container-2 || exit 1
            docker logs spring-boot-container-2
          EOF
